### ISSUE TITLE
Usage with `std::` types

### ISSUE THREAD

**Issue by TerensTare** [kuznetsss/pimpl_on_stack#1]
Hey there I recently heard of Antony Polukhin's Pimpl-on-stack method and found this implementation. I was wondering how to deduce the size of standard classes, since the size isn't stated by the standard. I specifically want to use `std::unordered_map<std::string, int, std::less<>>` and `std::mutex`. Any help is appreciated. Thanks in advance!

**Comment by kuznetsss** [comment]
Hi, the idea is that you don't need to guess the size of a class by yourself. You can use any number and at first compilation you will get failed [static_asserts](https://github.com/kuznetsss/pimpl_on_stack/blob/master/include/pimpl_on_stack/pimpl_on_stack.h#L60-L61) and there will be real size and real allocation in the compiler output. So it doesn't matter whether the size of a class you're using is specified or not.

**Comment by TerensTare** [comment]
The problem is that I am trying to write something cross-platform/cross-compiler and I think different implementation don't have the same size for `std::` types. Thanks anyway, I think I will use Compiler Explorer and some macros or sth to make it work.

**Comment by TerensTare** [comment]
I think I found the solution that is NOT painful. One can use a `static constexpr` function implemented on a source file that returns the size and one for the alignment of the desired type.

**Comment by kuznetsss** [comment]
Anyway with Pimpl-on-stack you will have to hardcode the sizes of your classes for all platforms/compilers. Maybe it's not a good idea to use Pimpl-on-stack when you're writing cross-platform/cross-compiler code.
